export const buyProperties = [
    {
      _id: 1,
      images: ['https://s1.1zoom.me/prev/426/425865.jpg'],
      location: {
        address: 'Calle Solitaria 789',
        city: 'Villa Tranquila',
        state: 'Pacífico',
      },
      description: 'Hermosa casa con vista al mar, ideal para disfrutar de la tranquilidad y el aire puro. Amplio jardín y espacios luminosos.',
      bedrooms: 5,
      bathrooms: 3,
      parking: true,
      price: 750000,
    },
    {
      _id: 2,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Boulevard de la Luz 300',
        city: 'Metropolis',
        state: 'Central',
      },
      description: 'Moderno departamento en el corazón de la ciudad, cerca de tiendas, restaurantes y entretenimiento. Vista panorámica desde el balcón.',
      bedrooms: 3,
      bathrooms: 2,
      parking: true,
      price: 550000,
    },
    {
      _id: 3,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Avenida del Bosque 55',
        city: 'Pueblo Verde',
        state: 'Natural',
      },
      description: 'Casa ecológica rodeada de naturaleza, con paneles solares y jardín de vegetales. Ideal para vivir de manera sustentable.',
      bedrooms: 4,
      bathrooms: 2,
      parking: false,
      price: 450000,
    },
    {
      _id: 4,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: '123 Main St, New York, NY',
        city: 'NYC',
        state: 'New York',
      },
      description: 'Elegante loft en el centro de Nueva York, con diseño industrial y grandes ventanales. Perfecto para una vida moderna en la gran ciudad.',
      bedrooms: 2,
      bathrooms: 1,
      parking: true,
      price: 850000,
    },
    {
      _id: 5,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Calle Jardín 101',
        city: 'Floralia',
        state: 'Primavera',
      },
      description: 'Casa de campo con amplio terreno y árboles frutales. Espacios acogedores y rústicos, perfecta para escapadas de la ciudad.',
      bedrooms: 3,
      bathrooms: 1,
      parking: true,
      price: 300000,
    },
];

export const rentProperties = [
    {
      _id: 1,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Plaza Central 10',
        city: 'Ciudad Vieja',
        state: 'Histórico',
      },
      description: 'Apartamento con encanto en el casco antiguo, con techos altos y detalles arquitectónicos originales. Cerca de museos y cafés.',
      bedrooms: 2,
      bathrooms: 1,
      parking: false,
      price: 1800,
    },
    {
      _id: 2,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: '123 Main St, New York, NY',
        city: 'NYC',
        state: 'New York',
      },
      description: 'Moderno estudio en Manhattan, con acceso a gimnasio y piscina en la azotea. Ubicación inmejorable para vivir y trabajar.',
      bedrooms: 1,
      bathrooms: 1,
      parking: true,
      price: 3000,
    },
    {
      _id: 3,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Calle del Río 45',
        city: 'Río Lindo',
        state: 'Aguas',
      },
      description: 'Apartamento con vista al río, ideal para amantes de la naturaleza. Terraza privada y acceso directo a senderos para caminatas.',
      bedrooms: 3,
      bathrooms: 2,
      parking: true,
      price: 2200,
    },
    {
      _id: 4,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Boulevard de la Luna 88',
        city: 'Nocturna',
        state: 'Cosmos',
      },
      description: 'Penthouse de lujo con vistas a la ciudad y al cielo nocturno. Decoración moderna y espacios amplios para eventos sociales.',
      bedrooms: 4,
      bathrooms: 3,
      parking: true,
      price: 5000,
    },
    {
      _id: 5,
      images: ['https://via.placeholder.com/600x400'],
      location: {
        address: 'Avenida del Parque 32',
        city: 'Ciudad Verde',
        state: 'Ecológico',
      },
      description: 'Condominio en una comunidad sostenible, con áreas verdes y espacios comunes. Perfecto para una vida comunitaria y saludable.',
      bedrooms: 2,
      bathrooms: 1,
      parking: false,
      price: 2000,
    },
];
